name: Compile Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Clone Proton Clang
      run: |
        git clone --depth=1 https://github.com/kdrag0n/proton-clang clang

    - name: Build kernel
      run: |
        export PATH="${PWD}/clang/bin:$PATH"
        export ARCH=arm64
        export SUBARCH=arm64
        make O=out ARCH=arm64 custom_defconfig
        cp arch/arm64/configs/custom_defconfig out/.config
        make O=out -j$(nproc) ARCH=arm64 CC=clang olddefconfig
        make O=out -j$(nproc) ARCH=arm64 \
          CC=clang \
          HOSTCC=gcc \
          HOSTCXX=g++ \
          LD=ld.lld

    - name: Clone AnyKernel3
      run: |
        git clone https://github.com/osm0sis/AnyKernel3.git anykernel
        cp out/arch/arm64/boot/Image anykernel/

    - name: Make flashable ZIP
      run: |
        cd anykernel
        zip -r9 ../kernel.zip *

    - name: Upload flashable ZIP
      uses: actions/upload-artifact@v4
      with:
        name: Kernel-Flashable-ZIP
        path: kernel.zip
